"""
Generate PDF incident report from session data using ReportLab.
"""
from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

ACCENT = colors.HexColor("#1a5276")


def generate_pdf(session: dict[str, Any]) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        name="ReportTitle",
        parent=styles["Heading1"],
        textColor=ACCENT,
        spaceAfter=6,
    )
    heading_style = ParagraphStyle(
        name="SectionHeading",
        parent=styles["Heading2"],
        textColor=ACCENT,
        spaceAfter=6,
    )

    story = []

    # Header
    story.append(Paragraph("Crisis Copilot Incident Report", title_style))
    report_id = session.get("session_id", "unknown")[:8]
    story.append(Paragraph(f"Report ID: {report_id}", styles["Normal"]))
    start = session.get("start_time", "")
    end = session.get("end_time") or "—"
    story.append(Paragraph(f"Date / time: {start}", styles["Normal"]))
    story.append(Paragraph(f"Session end: {end}", styles["Normal"]))
    meta_list = session.get("metadata_list") or []
    if meta_list:
        categories = [m.get("category") for m in meta_list if m.get("category")]
        urgencies = [m.get("urgency") for m in meta_list if m.get("urgency")]
        cat = max(set(categories), key=categories.count) if categories else "other"
        urgency = max(set(urgencies), key=urgencies.count) if urgencies else "medium"
        story.append(Paragraph(f"Category: {cat} | Urgency: {urgency}", styles["Normal"]))
    story.append(Spacer(1, 0.3 * inch))

    # Timeline
    story.append(Paragraph("Timeline of actions", heading_style))
    rows = [["Time", "Step", "Action / Instruction", "Urgency"]]
    assistant_msgs = [m for m in session.get("messages", []) if m.get("role") == "assistant"]
    for i, m in enumerate(assistant_msgs):
        ts = m.get("timestamp", "")[:19].replace("T", " ")
        meta = meta_list[i] if i < len(meta_list) else {}
        step = meta.get("step", "—")
        urgency = meta.get("urgency", "—")
        text = (m.get("text") or "")[:80] + ("..." if len(m.get("text") or "") > 80 else "")
        rows.append([ts, str(step), text, urgency])
    if len(rows) > 1:
        t = Table(rows, colWidths=[1.2 * inch, 0.5 * inch, 3.5 * inch, 0.8 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(t)
    story.append(Spacer(1, 0.3 * inch))

    # Full transcript
    story.append(Paragraph("Full transcript", heading_style))
    for m in session.get("messages", []):
        role = m.get("role", "user").upper()
        if role == "USER":
            label = "[USER]"
        elif role == "ASSISTANT":
            label = "[GUIDEVR]"
        else:
            label = f"[{role}]"
        ts = m.get("timestamp", "")[:19].replace("T", " ")
        text = (m.get("text") or "").replace("\n", " ")
        story.append(Paragraph(f"<b>{label}</b> {ts}", styles["Normal"]))
        story.append(Paragraph(text, styles["Normal"]))
        story.append(Spacer(1, 4))
    story.append(Spacer(1, 0.3 * inch))

    # Footer
    story.append(Paragraph(
        "This report was auto-generated by Crisis Copilot. It is not a medical or legal document.",
        styles["Normal"],
    ))
    story.append(Paragraph("For emergencies, always contact local emergency services.", styles["Normal"]))

    doc.build(story)
    return buffer.getvalue()
